line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "W", "I", "N", "UP"]

[lint.isort]
known-first-party = ["app"]

[format]

[lint.per-file-ignores]
"alembic/versions/*" = ["E501"]
