"""drop parents table

Revision ID: 011
Revises: 010
Create Date: 2026-04-27 21:25:16.552092

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "011"
down_revision: str | None = "010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parents_phone"), table_name="parents")
    op.drop_index(op.f("ix_parents_user_id"), table_name="parents")
    op.drop_table("parents")
    op.drop_index(op.f("ix_attendance_session_date"), table_name="attendance_records")
    op.drop_index(op.f("ix_attendance_student_id"), table_name="attendance_records")
    op.drop_constraint(op.f("uq_attendance_session_student_date"), "attendance_records", type_="unique")
    op.create_index(op.f("ix_attendance_records_session_date"), "attendance_records", ["session_date"], unique=False)
    op.create_index(op.f("ix_attendance_records_student_id"), "attendance_records", ["student_id"], unique=False)
    op.create_index(op.f("ix_payment_records_payment_date"), "payment_records", ["payment_date"], unique=False)
    op.drop_constraint(op.f("uq_renewal_package_number"), "renewal_reminders", type_="unique")
    op.drop_index(op.f("ix_teachers_user_id"), table_name="teachers")
    op.create_unique_constraint(None, "teachers", ["user_id"])
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_constraint(None, "teachers", type_="unique")
    op.create_index(op.f("ix_teachers_user_id"), "teachers", ["user_id"], unique=True)
    op.create_unique_constraint(
        op.f("uq_renewal_package_number"),
        "renewal_reminders",
        ["package_id", "reminder_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_payment_records_payment_date"), table_name="payment_records")
    op.drop_index(op.f("ix_attendance_records_student_id"), table_name="attendance_records")
    op.drop_index(op.f("ix_attendance_records_session_date"), table_name="attendance_records")
    op.create_unique_constraint(
        op.f("uq_attendance_session_student_date"),
        "attendance_records",
        ["class_session_id", "student_id", "session_date"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_attendance_student_id"), "attendance_records", ["student_id"], unique=False)
    op.create_index(op.f("ix_attendance_session_date"), "attendance_records", ["session_date"], unique=False)
    op.create_table(
        "parents",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("full_name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("phone_secondary", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("zalo_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("parents_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("parents_pkey")),
    )
    op.create_index(op.f("ix_parents_user_id"), "parents", ["user_id"], unique=True)
    op.create_index(op.f("ix_parents_phone"), "parents", ["phone"], unique=False)
    # ### end Alembic commands ###
