"""Add recurring pattern

Revision ID: 014
Revises: 013
Create Date: 2026-04-28 12:15:03.641347

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014"
down_revision: str | None = "013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_attendance_records_center_id"), "attendance_records", type_="foreignkey")
    op.create_foreign_key(None, "attendance_records", "centers", ["center_id"], ["id"])
    op.drop_constraint(op.f("uq_centers_code"), "centers", type_="unique")
    op.drop_constraint(op.f("uq_centers_name"), "centers", type_="unique")
    op.drop_index(op.f("ix_centers_code"), table_name="centers")
    op.create_index(op.f("ix_centers_code"), "centers", ["code"], unique=True)
    op.drop_index(op.f("ix_centers_name"), table_name="centers")
    op.create_index(op.f("ix_centers_name"), "centers", ["name"], unique=True)
    op.drop_constraint(op.f("fk_centers_registered_by_id"), "centers", type_="foreignkey")
    op.create_foreign_key(None, "centers", "users", ["registered_by_id"], ["id"])
    op.drop_constraint(op.f("fk_class_enrollments_center_id"), "class_enrollments", type_="foreignkey")
    op.create_foreign_key(None, "class_enrollments", "centers", ["center_id"], ["id"])
    op.add_column(
        "class_sessions", sa.Column("recurring_pattern", sa.String(length=50), server_default="weekly", nullable=False)
    )
    op.drop_constraint(op.f("fk_class_sessions_center_id"), "class_sessions", type_="foreignkey")
    op.create_foreign_key(None, "class_sessions", "centers", ["center_id"], ["id"])
    op.drop_index(op.f("uq_lesson_kind_name_normalized"), table_name="lesson_kinds")
    op.create_index(op.f("ix_lesson_kinds_name_normalized"), "lesson_kinds", ["name_normalized"], unique=True)
    op.drop_constraint(op.f("fk_lesson_kinds_center_id"), "lesson_kinds", type_="foreignkey")
    op.create_foreign_key(None, "lesson_kinds", "centers", ["center_id"], ["id"])
    op.drop_constraint(op.f("fk_packages_center_id"), "packages", type_="foreignkey")
    op.create_foreign_key(None, "packages", "centers", ["center_id"], ["id"])
    op.create_index(op.f("ix_payment_records_payment_date"), "payment_records", ["payment_date"], unique=False)
    op.drop_constraint(op.f("fk_payment_records_center_id"), "payment_records", type_="foreignkey")
    op.create_foreign_key(None, "payment_records", "centers", ["center_id"], ["id"])
    op.drop_constraint(op.f("uq_renewal_package_number"), "renewal_reminders", type_="unique")
    op.drop_constraint(op.f("fk_renewal_reminders_center_id"), "renewal_reminders", type_="foreignkey")
    op.create_foreign_key(None, "renewal_reminders", "centers", ["center_id"], ["id"])
    op.drop_constraint(op.f("fk_student_status_history_center_id"), "student_status_history", type_="foreignkey")
    op.create_foreign_key(None, "student_status_history", "centers", ["center_id"], ["id"])
    op.drop_constraint(op.f("fk_students_center_id"), "students", type_="foreignkey")
    op.create_foreign_key(None, "students", "centers", ["center_id"], ["id"])
    op.drop_constraint(op.f("fk_teachers_center_id"), "teachers", type_="foreignkey")
    op.create_foreign_key(None, "teachers", "centers", ["center_id"], ["id"])
    op.drop_constraint(op.f("fk_users_center_id"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "centers", ["center_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(op.f("fk_users_center_id"), "users", "centers", ["center_id"], ["id"], ondelete="RESTRICT")
    op.drop_constraint(None, "teachers", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_teachers_center_id"), "teachers", "centers", ["center_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(None, "students", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_students_center_id"), "students", "centers", ["center_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(None, "student_status_history", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_student_status_history_center_id"),
        "student_status_history",
        "centers",
        ["center_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(None, "renewal_reminders", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_renewal_reminders_center_id"),
        "renewal_reminders",
        "centers",
        ["center_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint(
        op.f("uq_renewal_package_number"),
        "renewal_reminders",
        ["package_id", "reminder_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "payment_records", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_payment_records_center_id"), "payment_records", "centers", ["center_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_index(op.f("ix_payment_records_payment_date"), table_name="payment_records")
    op.drop_constraint(None, "packages", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_packages_center_id"), "packages", "centers", ["center_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(None, "lesson_kinds", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_lesson_kinds_center_id"), "lesson_kinds", "centers", ["center_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_index(op.f("ix_lesson_kinds_name_normalized"), table_name="lesson_kinds")
    op.create_index(op.f("uq_lesson_kind_name_normalized"), "lesson_kinds", ["name_normalized"], unique=True)
    op.drop_constraint(None, "class_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_class_sessions_center_id"), "class_sessions", "centers", ["center_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_column("class_sessions", "recurring_pattern")
    op.drop_constraint(None, "class_enrollments", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_class_enrollments_center_id"),
        "class_enrollments",
        "centers",
        ["center_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(None, "centers", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_centers_registered_by_id"), "centers", "users", ["registered_by_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_index(op.f("ix_centers_name"), table_name="centers")
    op.create_index(op.f("ix_centers_name"), "centers", ["name"], unique=False)
    op.drop_index(op.f("ix_centers_code"), table_name="centers")
    op.create_index(op.f("ix_centers_code"), "centers", ["code"], unique=False)
    op.create_unique_constraint(op.f("uq_centers_name"), "centers", ["name"], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f("uq_centers_code"), "centers", ["code"], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, "attendance_records", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_attendance_records_center_id"),
        "attendance_records",
        "centers",
        ["center_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
