"""Add unique constraint to class sessions

Revision ID: 017
Revises: 016
Create Date: 2026-04-28 19:21:53.533031

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "017"
down_revision: str | None = "016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_class_session_center_name", "class_sessions", ["center_id", "name"])
    op.drop_index(op.f("ix_tuition_payments_payment_date"), table_name="tuition_payments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_tuition_payments_payment_date"), "tuition_payments", ["payment_date"], unique=False)
    op.drop_constraint("uq_class_session_center_name", "class_sessions", type_="unique")
    # ### end Alembic commands ###
