"""remove class name unique constraint

Revision ID: 019
Revises: 018
Create Date: 2026-04-29 15:40:42.070889

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '019'
down_revision: str | None = '018'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_class_session_center_name'), 'class_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_class_session_center_name'), 'class_sessions', ['center_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
