"""fix lesson kind uniqueness

Revision ID: 020
Revises: 019
Create Date: 2026-04-29 15:52:15.509703

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020"
down_revision: str | None = "019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lesson_kinds_name_normalized"), table_name="lesson_kinds")
    op.create_index(op.f("ix_lesson_kinds_name_normalized"), "lesson_kinds", ["name_normalized"], unique=False)
    op.create_unique_constraint("uq_lesson_kind_center_name", "lesson_kinds", ["center_id", "name_normalized"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_lesson_kind_center_name", "lesson_kinds", type_="unique")
    op.drop_index(op.f("ix_lesson_kinds_name_normalized"), table_name="lesson_kinds")
    op.create_index(op.f("ix_lesson_kinds_name_normalized"), "lesson_kinds", ["name_normalized"], unique=True)
    # ### end Alembic commands ###
