"""combine student notes

Revision ID: 023
Revises: 022
Create Date: 2026-05-03 01:32:30.820909

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "023"
down_revision: str | None = "022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_attendance_records_lesson_occurrence_id"), "attendance_records", ["lesson_occurrence_id"], unique=False
    )
    op.create_index(op.f("ix_class_enrollments_student_id"), "class_enrollments", ["student_id"], unique=False)
    op.create_index(op.f("ix_classes_lesson_kind_id"), "classes", ["lesson_kind_id"], unique=False)
    op.add_column("students", sa.Column("notes", sa.Text(), nullable=True))
    op.drop_column("students", "learning_speed")
    op.drop_column("students", "personality_notes")
    op.drop_column("students", "current_issues")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("current_issues", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("students", sa.Column("personality_notes", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("students", sa.Column("learning_speed", sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column("students", "notes")
    op.drop_index(op.f("ix_classes_lesson_kind_id"), table_name="classes")
    op.drop_index(op.f("ix_class_enrollments_student_id"), table_name="class_enrollments")
    op.drop_index(op.f("ix_attendance_records_lesson_occurrence_id"), table_name="attendance_records")
    # ### end Alembic commands ###
