"""make class teacher_id nullable

Revision ID: 024
Revises: 023
Create Date: 2026-05-06 23:10:58.219108

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '024'
down_revision: str | None = '023'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('classes_teacher_id_fkey'), 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key(op.f('classes_teacher_id_fkey'), 'classes', 'teachers', ['teacher_id'], ['id'])
    op.alter_column('classes', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
